"""001_initial_schema

Revision ID: ccfac3936ecc
Revises: 
Create Date: 2026-06-12 13:13:01.178532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfac3936ecc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_telemtry_events_session_id_server_ts", "telemetry_events", ["student_session_id", "server_ts"], unique=False)
    op.create_index("ix_student_sessions_exam_session_id_student_id", "student_sessions", ["exam_session_id", "student_id"], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_telemtry_events_session_id_server_ts", table_name="telemetry_events")
    op.drop_index("ix_student_sessions_exam_session_id_student_id", table_name="student_sessions")
    pass
    # ### end Alembic commands ###
